### ISSUE TITLE
UpdateRoll not working

### ISSUE THREAD

**Issue by psp515** [Deve-Lite/3DPH.Api#6]
![image](https://user-images.githubusercontent.com/69080157/133786471-112cb1b8-5d47-4834-9749-6aa3643c368a.png)

1. Na updacie id jest potrzebne wiec nie rozumiem dlaczego tu pojawia sie ze to pole nie powinno istniec
2. key, colorhex do porawki 
3. Nie da sie cos z tym zrobic zeby nie wyrzucalo erroru jak wysylam np editedat i createdat?  Bo w c# to sa nie nullable typy i przy skladanu jsona ich nie pomija tylko je tworzy po prostu z wartoscia 0 (Tak samo dla add, fajnie by bylo zeby tych 2 pól nie wurzucalo bo musze w sumie robic 2 prawie taka samą klase)

**Comment by psp515** [comment]
w sumie 1 i 3 jakos rozwiazałem wiec 2 pkt do porawy

**Comment by dredziasty** [comment]
1. Id wysyłane jest w URLu, nie body
3. Te pola uzupełnia API, wtedy kiedy zapisuje / updateuje rolla

2. Ok
