### ISSUE TITLE
AddRollWeirdo

### ISSUE THREAD

**Issue by psp515** [Deve-Lite/3DPH.Api#7]
![image](https://user-images.githubusercontent.com/69080157/133791225-ac8cbac9-6917-4c12-b431-a026ddb6c653.png)

ale nie dalo by sie tu  zamiast "value->roll-> pola roll" zrobic np "value -> pola roll" tak jak na getRoll
dlaczego ? bo musze tworzyc kolejny obiekty konwersji Jsona i sie troche smietnik robi

**Comment by dredziasty** [comment]
Zauważ, że chciałeś, żebym zwracał Ci grupę i roll'a z endpoint'a `getRoll`, musiałem połączyć jakoś dwa interfejsy w jeden typ danych, żeby Ci to zwrócić.
