### ISSUE TITLE
AddRollError

### ISSUE THREAD

**Issue by psp515** [Deve-Lite/3DPH.Api#8]
![image](https://user-images.githubusercontent.com/69080157/134345591-74e1ba7e-265a-4027-a872-81ebd59ce8b7.png)

filamentCoolingSpeed,filamentPrintingTemperature,filamentBedTemperature powiny dzialać w zakresie od 0

**Comment by psp515** [comment]
Od razu można sprawdzic czy tak tez jest na updacie

**Comment by dredziasty** [comment]
Zmienione
